export const NAVIGATION = {
  CHANGE_HEADER: 'NAVIGATION.CHANGE_HEADER',
};

export const USER_REQUEST = {
  SUCCESS: 'USER_REQUEST.SUCCESS',
  FAIL: 'USER_REQUEST.FAIL',
  LOADING: 'USER_REQUEST.LOADING',
};

export const PAYMENT = {
  SUCCESS: 'PAYMENT.SUCCESS',
  FAIL: 'PAYMENT.FAIL',
  LOADING: 'PAYMENT.LOADING',
};

export const HISTORY_RESPONSE = {
  SUCCESS: 'HISTORY_RESPONSE.SUCCESS',
  FAIL: 'HISTORY_RESPONSE.FAIL',
  LOADING: 'HISTORY_RESPONSE.LOADING',
};

export const CAPTCHA = {
  SUCCESS: 'CAPTCHA.SUCCESS',
  FAIL: 'CAPTCHA.FAIL',
  LOADING: 'CAPTCHA.LOADING',
};

export const REFRESH_KEY = {
  SUCCESS: 'REFRESH_KEY.SUCCESS',
  FAIL: 'REFRESH_KEY.FAIL',
  LOADING: 'REFRESH_KEY.LOADING',
};

export const LOGIN_UPDATE = {
  SUCCESS: 'LOGIN_UPDATE.SUCCESS',
  FAIL: 'LOGIN_UPDATE.FAIL',
  LOADING: 'LOGIN_UPDATE.LOADING',
};

export const LOGIN = {
  SUCCESS: 'LOGIN.SUCCESS',
  FAIL: 'LOGIN.FAIL',
};

export const SIGNUP = {
  SUCCESS: 'SIGNUP.SUCCESS',
  FAIL: 'SIGNUP.FAIL',
};

export const AUTH = {
  SET_DATA: 'AUTH.SET_DATA',
};
