export const NAVIGATION = {
  CHANGE_HEADER: 'NAVIGATION.CHANGE_HEADER',
};

export const USER_REQUEST = {
  SUCCESS: 'USER_REQUEST.SUCCESS',
  FAIL: 'USER_REQUEST.FAIL',
  LOADING: 'USER_REQUEST.LOADING',
};

export const LOGIN = {
  SUCCESS: 'LOGIN.SUCCESS',
  FAIL: 'LOGIN.FAIL',
};
