export const APP_PAGE_ID = 'APP_PAGE';

export const FORM_NAMES = {
  USER_REQUEST: 'FORM.USER_REQUEST',
  LOGIN: 'FORM.LOGIN',
  SIGNUP: 'FORM.SIGNUP',
  REFRESH_KEY: 'FORM.REFRESH_KEY',
  LOGIN_UPDATE: 'FORM.LOGIN_UPDATE',
};

export const COOKIE_AUTH = 'COOKIE_AUTH';
