export const PAGE_TYPE = {
  HOME: 'HOME',
  RESPONSE: 'RESPONSE',
  LOGIN: 'LOGIN',
  SIGNUP: 'SIGNUP',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SETTINGS: 'SETTINGS',
  HISTORY: 'HISTORY',
};

export const REQUEST_DATA_TYPE = {
  EMAIL: 'EMAIL',
  PHONE: 'PHONE',
  NAME: 'NAME',
  ID: 'ID',
};
